/* Turns an export of the editor's database into src/copy.data.js.

     Claude: Artifact read_db (collection "copy", out_dir <dir>)
     node scripts/pull-copy.mjs <dir>

   Each document is one group, keyed by field path with dots swapped for
   double underscores. Empty values mean "use whatever content.js says",
   so they are dropped rather than written as blanks. */
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { deck, meta, chapters } from '../src/content.js'
import { walk } from '../src/copy.js'

const dir = process.argv[2]
if (!dir) { console.error('usage: node scripts/pull-copy.mjs <dir of exported json>'); process.exit(1) }

const files = []
const find = d => { for (const e of readdirSync(d)) {
  const p = join(d, e)
  if (statSync(p).isDirectory()) find(p); else if (e.endsWith('.json')) files.push(p)
} }
find(dir)

const known = new Set(walk(deck, meta, chapters).map(f => f.path))
const out = {}
let skipped = 0, blank = 0
for (const f of files) {
  const doc = JSON.parse(readFileSync(f, 'utf8'))
  const fields = doc.data && typeof doc.data === 'object' ? doc.data : doc
  for (const [key, value] of Object.entries(fields)) {
    if (key.startsWith('__') || typeof value !== 'string') continue
    const path = key.replace(/__/g, '.')
    if (!known.has(path)) { skipped++; continue }       // a path the deck no longer has
    if (!value.trim()) { blank++; continue }
    out[path] = value
  }
}

const sorted = Object.fromEntries(Object.keys(out).sort().map(k => [k, out[k]]))
writeFileSync(new URL('../src/copy.data.js', import.meta.url).pathname,
  '/* Text edited in the live editor. Generated by `npm run pull-copy` —\n' +
  '   do not hand-edit. Paths absent here keep the default wording in\n' +
  '   content.js. */\nexport default ' + JSON.stringify(sorted, null, 2) + '\n')

console.log(`${files.length} document(s) read`)
console.log(`${Object.keys(sorted).length} override(s) written to src/copy.data.js`)
if (blank) console.log(`${blank} left at the site default`)
if (skipped) console.log(`${skipped} ignored — path no longer in the deck`)
